### PR TITLE
Ability to preload additional custom services

### PR DESCRIPTION
**Pull request by vlad-ignatov**
I am working on the SMART App Launcher (http://launch.smarthealthit.org/), adding support for CDS Hooks as new "launch type". In this mode people enter an URL that points to their service discovery endpoint and then click a button that launches the CDS sandbox as SMART app in new tab. By launching it as app we already have the auth handled and the `fhirBaseUrl` properly set up. The only missing piece was a way to "inject" the user's service discovery URL and to add the new services to the list. We implemented this by returning new custom property called `serviceDiscoveryURL` to the access token response. This way, when the sandbox authorizes itself, it will already know if new service will have to be loaded and load them before the initial render.

I kept the code changes to the minimum and it should not affect the CDS Sandbox in any way. However, we do introduce new proprietary property to the auth token response. I hope other parties might be interested in this as well.

### CODE REVIEW

**Comment by zplata** [comment]
Thanks @vlad-ignatov ! I tested this change out and it looks good, just one small comment. Can you run `npm run build` to generate a new bundled JS file so it will incorporate this change?

**Comment by vlad-ignatov** [comment]
Thanks, I did that. I couldn't find a way to reliably diff 4MB single line file so I'm not 100% confident with this change but at least it works and the test are passing :)

**Comment by zplata** [comment]
No worries, no need to diff review that file. It's main purpose is to capture all the JS in the application, with your new change incorporated in it. So as long as that command was run, we just commit that in the repository and it should be good to go.

**Review by zplata — APPROVED** [review]

**Review by kpshek — APPROVED** [review]
Thanks for the PR @vlad-ignatov!

**Comment by vlad-ignatov** [comment]
Thanks! I deployed the other part to our staging server and it works. In case you are curious, you can try it at https://smart-launcher-staging.herokuapp.com/?launch_cds=1&patient=04327b09-4d3a-4c8b-9959-83bc1b358203&provider=SMART-1234

**Comment by barabo** [comment]
TODO:

- [x] enable a CI/CD pipeline to deploy the sandbox-cds-services.
- [ ] populate the default service to reference the public service.

**Comment by dennispatterson** [comment]
sandbox-cds-services will build and deploy to GCP - https://github.com/cds-hooks/sandbox-cds-services/blob/master/.travis.yml . Are you looking for something else for that first bullet?

**Pull request merged**
