### PR TITLE
Rename app to CDS Hooks Sandbox and change CDS_HOOKS_URL and FHIR_URL in webpack config. Fixes #16

### LINKED ISSUE #16: Rename app to CDS Hooks Sandbox
Currently, we're using demo.cds-hooks.org and "CDS Hooks Demo". While this is a demo, we always just refer to this as the "CDS Hooks Sandbox" or "CDS Hooks Test Harness". While this app can be used for a demo, sandbox is a more appropriate name. Additionally, the concept of a sandbox is well understood in both the SMART and FHIR communication.

Acceptance criteria:
- Rename the site to "CDS Hooks Sandbox"
- Redeploy to sandbox.cds-hooks.org

After this change is made I think it would be good to rename the repository to `cds-hooks-sandbox`

### PR DESCRIPTION
**Pull request by zplata**
Currently, the tool is using demo.cds-hooks.org and "CDS Hooks Demo". While this is a demo, we always just refer to this as the "CDS Hooks Sandbox". While this app can be used for a demo, sandbox is a more appropriate name. Additionally, the concept of a sandbox is well understood in both the SMART and FHIR communication.

Additionally, we should update the FHIR server referenced to SMART's latest sandbox and update the `CDS_HOOKS_URL` in production to where the sample CDS Services are hosted, at http://hooks.fhir.me:8082.

### CODE REVIEW

**Review by kpshek — APPROVED** [review]
Thanks @zplata!

@jmandel - can you review too please?

**Comment by kpshek** [comment]
@jmandel - fyi, you can see all of the changes from @zplata from the @Cerner fork `gh-pages` deployment at http://engineering.cerner.com/cds-hooks-sandbox

**Comment by jmandel** [comment]
When I ctrl-click the http://engineering.cerner.com/cds-hooks-sandbox above (to open in a new tab), it automatically closes itself :/

Opening a new tab and then loading the site directly works fine, and the site works as expected :-)

**Comment by kpshek** [comment]
> When I ctrl-click the http://engineering.cerner.com/cds-hooks-sandbox above (to open in a new tab), it automatically closes itself :/

@zplata - I'm seeing this too in Chrome but not Firefox. You?

**Comment by zplata** [comment]
@kpshek @jmandel , It could be a pre-existing defect within the application itself - as I get the same behavior when navigating in the same manner to the sandbox from http://cds-hooks.org/#try-it? Does that happen for either of you on that link too?

**Comment by jmandel** [comment]
I actually don't get that behavior from the link on cds-hooks.org/#try-it (I checked that before submitting the initial report). Weird.

**Pull request merged**
