### PR TITLE
Fix for familyName for dst3 and dstu2

### PR DESCRIPTION
**Pull request by anoush-bch**
Making name[0].famly work both for dstu3 (when it’s a string) and dstu2 (when it’s an array).

### CODE REVIEW

**Review by kpshek — APPROVED** [review]
Thank you Anoush! One @zplata reviews I'll merge this in.

**Comment by zplata** [comment]
@anoush-bch Thanks for adding this check! Would you mind running `npm run build` at the base level of the project? This will generate a `bundle.js` file in the `build` folder, which is what ultimately gets read on the deployed webpage.

**Comment by anoush-bch** [comment]
@zplata , I ran npm run build and can see /build/bundle.js on my local, did you want me to push it in?

**Comment by zplata** [comment]
@anoush-bch Yes that'd be great. That way, the `master` branch has your code in the updated bundle on the `build` folder.

**Comment by anoush-bch** [comment]
@zplata I pushed in bundle.js to familyNameFix branch, let me know if you need anything else - would another pull request be needed?

**Comment by zplata** [comment]
Nope, that should be all. We'll update the documentation for the future to make the build step clearer. Thanks @anoush-bch! @kpshek we should be good to merge this in.

**Pull request merged**
